# configuration
dist: bionic
sudo: required
language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  npm: true
  directories:
  - $HOME/.m2
  - core/new_gui/node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:canonical-chromium-builds/stage -y
  - sudo apt-get update
  - sudo apt-get install chromium-browser -y
  - export CHROME_BIN=chromium-browser
  - export LC_ALL=C
  - sudo apt-get install python3-pip
  - sudo pip3 install setuptools -U
  - sudo pip3 install nltk -U
  - nvm install --lts
  - nvm use --lts
   
# run steps
install:
  - cd core 
  - cd new-gui
  - npm ci
  - cd ..

script:
  - mvn clean install --batch-mode
  - cd new-gui
  - npm run build-no-progress
  # - ng test --browsers ChromeHeadless --watch=false
  # - ng e2e
  
